### ISSUE TITLE
Does this work on Server 2022?

### ISSUE THREAD

**Issue by Kyri304** [ahelland/ADFSMFAAdapters#10]
Hi,

I got the C:\Windows\ADFS\Microsoft.IdentityServer.Web.dll from my ADFS server 2022 but I can't compile it for some reason.
I am not familiar with compiling coding etc but when I run the solution form VS I get the "A project with an Output type of Class Library cannot be started directly"
I followed the instructions on this link (https://stackoverflow.com/questions/3363106/a-project-with-an-output-type-of-class-library-cannot-be-started-directly) but made no changes.
I have made the YubiKeyMFAAdapter as a "Startup Project" too but it still failed to compile?.
Am I missing something?

Also does this work on ADFS Server 2022?

**Comment by ahelland** [comment]
I have not tested this adapter on Windows Server 2022, but seeing as ADFS 2022 and 2019 are more or less identical I don't see why it wouldn't work. Do let me know if that is not the case and you're seeing errors.

Since it is a dll that is the output of the solution you cannot use the "Run" command in Visual Studio. If you do a Build command you should get a dll as the output and that needs to be copied to the ADFS server for actual testing. (Which is slightly clunky, but it is what it is.)

I just added a "Release" folder with the compiled dll so if you like you can use that instead of figuring out Visual Studio:
https://github.com/ahelland/ADFSMFAAdapters/tree/master/YubiKeyMFAAdapter/Release
