### ISSUE TITLE
Support for TLSv1.2

### ISSUE THREAD

**Issue by ClosedCondition** [ahelland/ADFSMFAAdapters#5]
Since [https://api.yubico.com](url) is not supporting TLS earlier than v1.2 anymore, it essential to explicitly add support for TLSv.1.2 to the code. 
Add this line: ` System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;` somewhere at the begin of ValidateProofData function in YubiKeyMFAAdapter.cs

Without the support of TLS1.2 the call of client.GetAsync OTP validating request against api.yubico.com URL will through exception with a message `An existing connection was forcibly closed by the remote host`

**Comment by ahelland** [comment]
Yeah, TLS with a lesser version than 1.2 isn't cutting it these days. This seems to be an issue here since I was using an older .NET version. 

From .NET 4.7 ServicePointManager should use the default of the OS, and unless you're using a very old OS version or have manually configured things differently this should be 1.2.

When testing with a newer .NET version on Windows Server 2019 it seems to be able to make the calls without explicit config so I'll update the code accordingly and push a new version.
